ativo/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.ativo, name='ativo'),
    path('add/', views.add, name='add'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ativo.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ativo/models.py
from django.db import models


class Corretora(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.nome


OPERACAO_CHOICES = (
    ('R', 'Retirada'),
    ('A', 'Aporte')
)


class Ativo(models.Model):
    ativo = models.CharField(max_length=6)
    corretora = models.ForeignKey(Corretora, on_delete=models.DO_NOTHING, related_name="corretora")
    valor_unitario = models.DecimalField(max_digits=8, decimal_places=2)
    data_compra = models.DateField()
    taxa = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    cotacao_atual = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    tipo_de_operacao = models.CharField(max_length=1, choices=OPERACAO_CHOICES)
    quantidade = models.IntegerField()
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.ativo
    
    def total_aplicado_por_movimentacao(self):
        return self.valor_unitario * self.quantidade + self.taxa
    
    

ativo/forms.py
from .models import Ativo
from django import forms


OPERACAO_CHOICES = (
    ('R', 'Retirada'),
    ('A', 'Aporte')
)


class AtivoForm(forms.ModelForm):
    class Meta:
        model = Ativo
        fields = ['tipo_de_operacao', 'ativo', 'corretora', 'valor_unitario', 'data_compra', 'taxa', 'quantidade']
        widgets = {
            'tipo_de_operacao': forms.Select(attrs={'class': 'form-control'}),
            'ativo': forms.TextInput(attrs={'class': 'form-control'}),
            'corretora': forms.Select(attrs={'class': 'form-control'}),
            'valor_unitario': forms.NumberInput(attrs={'class': 'form-control'}),
            'data_compra': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'taxa': forms.NumberInput(attrs={'class': 'form-control'}),
            'quantidade': forms.NumberInput(attrs={'class': 'form-control'}),
        }

ativo/views.py
from django.shortcuts import render, redirect
from .models import Ativo, Corretora
from .forms import AtivoForm
from django.db.models import Sum, F
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import requests
import json


def get_cotacao(ticker):
    url = f'https://brapi.dev/api/quote/{ticker}'
    response = requests.get(url)
    data = json.loads(response.content)

    return data['results'][0]['regularMarketPrice']



def index(request):
    movimentacoes = Ativo.objects.all().order_by('-criado_em')


    # valores_aplicados = Ativo.objects.values('ativo').annotate(
    #     total=Sum(
	#         F('valor_unitario') * F('quantidade')
    #     )
    # )

    # ativos = Ativo.objects.all()

    # print(valores_aplicados)
    # # print(ativos)

    

    return render(request, 'index.html', {'movimentacoes': movimentacoes})
    

def ativo(request):

    return redirect('index')


def add(request):
    form = AtivoForm()

    if request.method == "POST":
        form = AtivoForm(request.POST)

        form.save()

        return redirect('index')
    

    return render(request, 'add.html', {'form': form})

def delete(request, pk):
    movimentacao = Ativo.objects.get(id=pk)

    if request.method == "POST":
        movimentacao.delete()

    return redirect('index')
    

ativo/templates/add.html
{% extends 'base.html' %}

{% block body %}

<h3 class="text-center m-4">Adicionar Ativo</h3>
{% if success %}
  <div class="alert alert-success" role="alert">
    O novo ativo foi adicionado com sucesso
    <a href="{% url 'index' %}" class="alert-link">Ir para Página Inicial</a>
  </div>
{% else %}
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="card bg-light mb-3">
        <div class="card-header">
          <i class="fa-solid fa-address-card fa-lg"></i> Student Registration
        </div>
        <div class="card-body">
          <form action="{% url 'add' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary mt-2">Adicionar</button>
            <a href="{% url 'index' %}" class="btn btn-secondary mt-2">Cancelar</a>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endif %}

{% endblock body %}

ativo/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="pt-BR">
  <head>
    <title>Gerenciador de Carteira de Investimentos</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body class="d-flex flex-column min-vh-100">
    {% include "nav.html" %}
    <div class="container-fluid">
      {% block body %}
      {% endblock %}
    </div>
    {% include "footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

  </body>
</html>

ativo/templates/footer.html
<footer class="mt-auto mb-4">
    <div class="text-center">
      <span>
        Copyright &copy; <script>document.write(new Date().getFullYear())</script> Criado por Diego.
      </span>
    </div>
  </footer>

ativo/templates/index.html
{% extends 'base.html' %}

{% block body %}
<h3 class="m-4">Movimentações</h3>
<div class="row">
  <div class="col-12">
    {% if movimentacoes %}
    <div class="card bg-light ms-4 me-4 mb-4">
      <div class="card-header">
        <i class="fa-solid fa-list fa-lg"></i> Todas as movimentações
      </div>
      <div class="card-body">
        <p class="card-text">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Nome</th>
                  <th scope="col">Tipo</th>
                  <th scope="col">Data</th>
                  <th scope="col">Quantidade</th>
                  <th scope="col">Valor unitário</th>
                  <th scope="col">Taxas</th>
                  <th scope="col">Total</th>
                  <th scope="col">Corretora</th>
                  <th scope="col">Ações</th>
                </tr>
              </thead>
              <tbody>
                {% for ativo in movimentacoes %}
                  <tr>
                    <td>{{ ativo.ativo }}</td>
                    {% if ativo.tipo_de_operacao == "A" %}
                      <td><span class="badge bg-success">{{ ativo.get_tipo_de_operacao_display }}</span></td>
                    {% else %}
                      <td><span class="badge bg-danger">{{ ativo.get_tipo_de_operacao_display }}</span></td>
                    {% endif %}
                    <td>{{ ativo.data_compra|date:"d/m/Y" }}</td>
                    <td>{{ ativo.quantidade }}</td>
                    <td>R$ {{ ativo.valor_unitario|floatformat:2 }}</td>
                    <td>R$ {{ ativo.taxa|floatformat:2 }}</td>
                    <td>R$ {{ ativo.total_aplicado_por_movimentacao|floatformat:2 }}</td>
                    <td>{{ ativo.corretora.nome}}</td>
                    

                    <td>
                      <button type="button" class="btn btn-success me-1" href="" data-bs-toggle="modal" data-bs-target="#myModal{{ativo.id}}">
                        <i class="fa-solid fa-circle-info fa-lg"></i>
                      </button>
                      

                      <!-- Modal - View Transaction -->
                      {% include "modal_view_transaction.html" %}

                      <button type="button" class="btn btn-warning me-1" data-bs-toggle="modal" data-bs-target="#myModalEdit{{ativo.id}}">
                        <i class="fa-solid fa-pen-to-square fa-lg"></i>
                      </button>

                      <!-- Modal - Edit Transaction -->

                      <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#myModalDelete{{ativo.id}}">
                        <i class="fa-solid fa-trash-can fa-lg"></i>
                      </button>
                    
                      <!-- Modal - Delete Transaction -->
                      {% include "modal_delete_transaction.html" %}
                    </td>
                  </tr>
                {% endfor %}
                
              </tbody>
            </table>
            {% include "pagination.html" %}
          </div>
        </p>
      </div>
    </div>
    {% else %}
      <h5 class="alert alert-primary ms-4 me-4">Não há ativos para exibir.</h5>
    {% endif %}
  </div>
</div>


{% endblock body %}

ativo/templates/modal_delete_transaction.html
<div class="modal" id="myModalDelete{{ativo.id}}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            Student: {{ student.first_name }} {{ student.last_name }}
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
          <p>Tem certeza de que quer excluir esta movimentação?</p>
        </div>
        <div class="modal-footer">
          <form action="{% url "delete" ativo.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
          </form>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

ativo/templates/modal_view_transaction.html
<div class="modal" id="myModal{{ativo.id}}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            Student: {{ ativo.ativo }}
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
          <ul class="list-unstyled">
            <li>Ativo: <strong>{{ ativo.ativo }}</strong></li>
            <li>First Name: <strong>{{ student.first_name }}</strong></li>
            <li>Last Name: <strong>{{ student.last_name }}</strong></li>
            <li>Email: <strong>{{ student.email }}</strong></li>
            <li>Field of Study: <strong>{{ student.field_of_study }}</strong></li>
            <li>GPA: <strong>{{ student.gpa }}</strong></li>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

ativo/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">
        <i class="fa-solid fa-bag-shopping"></i> Cateira de Investimento
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">
              <i class="fa-solid fa-list fa-lg"></i> Todas as Movimentações
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'add' %}">
              <i class="fa-solid fa-plus fa-lg"></i> Nova Transação
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

ativo/templates/pagination.html
<nav class="justify-content-end">
    <ul class="pagination">
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item active" aria-current="page">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
    </ul>
  </nav>